name: payload
description: "A powerful API testing tool with WebSocket support."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  flutter_riverpod: ^3.2.0
  google_fonts: ^7.0.2
  flutter_animate: ^4.5.0
  web_socket_channel: ^3.0.3
  path_provider: ^2.1.2
  flutter_widget_from_html: ^0.17.1
  file_picker: ^10.3.8
  go_router: ^17.0.1
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  google_mobile_ads: ^7.0.0
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/app_logo.png
    - assets/app_icon.png
